#!/bin/bash

AOUT=$(basename --suffix='.c' $1);

gcc \
 -Wall -Wextra -Wpedantic -Werror \
 -ggdb \
 $CFLAGS \
 -include alloca.h \
 -include assert.h \
 -include complex.h \
 -include endian.h \
 -include errno.h \
 -include execinfo.h \
 -include fcntl.h \
 -include float.h \
 -include getopt.h \
 -include limits.h \
 -include math.h \
 -include pthread.h \
 -include stdarg.h \
 -include stdatomic.h \
 -include stdint.h \
 -include stdio.h \
 -include stdlib.h \
 -include string.h \
 -include strings.h \
 -include sys/mman.h \
 -include sys/stat.h \
 -include sys/syscall.h \
 -include sys/time.h \
 -include termios.h \
 -include time.h \
 -include unistd.h \
 -o $AOUT \
 $1 && ls -l $AOUT
