#!/bin/bash

AOUT=$(basename --suffix='.c' $1);

#NOISY_FLAGS='-Wall -Wextra -Wpedantic -Werror'
NOISY_FLAGS='-Wall -Wextra -Wpedantic'

gcc \
 $CFLAGS \
 $NOISY_FLAGS \
 -ggdb -pipe \
 $CFLAGS \
 -include alloca.h \
 -include assert.h \
 -include complex.h \
 -include endian.h \
 -include errno.h \
 -include execinfo.h \
 -include fcntl.h \
 -include float.h \
 -include getopt.h \
 -include limits.h \
 -include math.h \
 -include pthread.h \
 -include stdarg.h \
 -include stdatomic.h \
 -include stdint.h \
 -include stdio.h \
 -include stdlib.h \
 -include string.h \
 -include strings.h \
 -include sys/mman.h \
 -include sys/stat.h \
 -include sys/syscall.h \
 -include sys/time.h \
 -include termios.h \
 -include time.h \
 -include unistd.h \
 -o $AOUT \
 $1 -lm -lpthread $LDFLAGS && \
 ls -l $AOUT
