#!/bin/bash

if [ "_${VERBOSE}_" != "__" ]; then
set -x
fi

if [ -f /usr/include/SDL2/SDL.h ]; then
SDL2_CFLAGS=`sdl2-config --cflags`
SDL2_LIBS=`sdl2-config --libs`
fi

if [ -f /usr/include/vulkan/vulkan.h ]; then
VULKAN_LIBS=-lvulkan
fi

AOUT=$(basename --suffix='.c' $1);

#NOISY_FLAGS='-Wall -Wextra -Wpedantic -Werror'
NOISY_FLAGS='-Wall -Wextra -Wpedantic'

# -Wl,--gc-sections,--print-gc-sections
gcc \
 $NOISY_FLAGS \
 -flto \
 -fdata-sections \
 -ffunction-sections \
 -Wl,--gc-sections \
 -ggdb -pipe \
 $SDL2_CFLAGS \
 -include alloca.h \
 -include assert.h \
 -include complex.h \
 -include endian.h \
 -include errno.h \
 -include execinfo.h \
 -include fcntl.h \
 -include float.h \
 -include getopt.h \
 -include limits.h \
 -include math.h \
 -include pthread.h \
 -include stdarg.h \
 -include stdatomic.h \
 -include stdint.h \
 -include stdio.h \
 -include stdlib.h \
 -include string.h \
 -include strings.h \
 -include sys/mman.h \
 -include sys/stat.h \
 -include sys/syscall.h \
 -include sys/time.h \
 -include termios.h \
 -include time.h \
 -include unistd.h \
 $CFLAGS \
 -o $AOUT \
 $1 -lm -lpthread -ldl $SDL2_LIBS $VULKAN_LIBS $LDFLAGS && \
 ls -l $AOUT
