#!/bin/bash

# df -h | head -n1 &&  df -h | grep '^/dev' | sort -r -k 4 -h
# | sort

# | sort --reverse --key=4 --human-numeric-sort
df --human-readable | head --lines=1 \
&& df --human-readable \
	| grep '^/dev' \
	| sort --key=6
