#!/bin/bash

INDENT=indent

# http://www.gnu.org/prep/standards/standards.html#Formatting
GINDENT='indent -nbad -bap -nbc -bbo -bl -bli2 -bls -ncdb -nce -cp1 -cs -di2 -ndj -nfc1 -nfca -hnl -i2 -ip5 -lp -pcs -psl -nsc -nsob'

$GINDENT -T FILE -T size_t "$@"
