#!/bin/bash
GIT_VERSION=`git --version | cut -f3 -d' '`

DARN=1;
while [ $DARN -ne 0 ]
do
  UNSTAGED_FILES=$(git status --untracked-files=no --short | wc --lines)
  if [ $UNSTAGED_FILES -ne 0 ]; then
      echo >&2 $'\x07'"Error: repository contains unstaged changes; exiting."
      exit 1
  fi

  if [ "$GIT_VERSION" \> "2.18" ]; then
      git pull --rebase=merges && git push; DARN=$?
  elif [ "$GIT_VERSION" \> "2.1" ]; then
      git pull --rebase=preserve && git push; DARN=$?
  else
      git fetch && git rebase --preserve-merges && git push; DARN=$?
  fi
done
