#!/bin/bash

while getopts ":b:d:p:l:z:" opt; do
	case $opt in
	b)
		BASE_DIR="$OPTARG"
		;;
	p)
		PORT="$OPTARG"
		;;
	d)
		DATA_DIR="$OPTARG"
		;;
	l)
		LOG_DIR="$OPTARG"
		;;
	z)
		LAUNCH_PREFIX="$OPTARG"
		;;
	\?)
		echo "Unknown Option: -$OPTARG" >&2
		exit 1
		;;
	:)
		echo "Option -$OPTARG requires an argument" >&2
		exit 1
		;;
	esac
done

if [ "_${BASE_DIR}_" == "__" ]; then
	BASE_DIR=$1
fi
if [ "_${BASE_DIR}_" == "__" ]; then
	if [ -e ${HOME}/builds/mariadb-server ]; then
		BASE_DIR=${HOME}/builds/mariadb-server
	elif [ -e ${HOME}/builds/mysql-server ]; then
		BASE_DIR=${HOME}/builds/mysql-server
	else
		echo "Option '-b basedir' not set, exiting'"
		exit 1
	fi
	echo "Option '-b basedir' not set, defaulting to '${BASE_DIR}'"
fi
BASE_DIR=`readlink -vf "${BASE_DIR}"`

if [ "_${PORT}_" == "__" ]; then
	PORT=$2
fi
if [ "_${PORT}_" == "__" ]; then
	PORT=13306
	echo "Option '-p port' not set, defaulting to $PORT"
fi


if [ "_${DATA_DIR}_" == "__" ]; then
	DATA_DIR=${BASE_DIR}/data
fi
if [ -e "${DATA_DIR}" ]; then
	DATA_DIR=`readlink -vf "${DATA_DIR}"`
else
	echo "DATA_DIR '${DATA_DIR}' does not exist, set wtih '-d'"
	if [ -e "${BASE_DIR}/scripts/mariadb-install-db" ]; then
		echo "forgot ${BASE_DIR}/scripts/mariadb-install-db ?"
	elif [ -e "${BASE_DIR}/scripts/mysql_install_db" ]; then
		echo "forgot ${BASE_DIR}/scripts/mariadb-install-db ?"
	fi
	exit 1
fi

if [ -e ${BASE_DIR}/libexec/mariadbd ]; then
	DB_EXE_PATH=${BASE_DIR}/libexec/mariadbd
elif [ -e ${BASE_DIR}/bin/mariadbd ]; then
	DB_EXE_PATH=${BASE_DIR}/bin/mariadbd
elif [ -e ${BASE_DIR}/libexec/mysqld ]; then
	DB_EXE_PATH=${BASE_DIR}/libexec/mysqld
elif [ -e ${BASE_DIR}/bin/mysqld ]; then
	DB_EXE_PATH=${BASE_DIR}/bin/mysqld
else
	echo "can not find db server executable in ${BASE_DIR}"
	exit 1;
fi
DB_EXE_PATH=`readlink -vf "$DB_EXE_PATH"`

if [ "_${LOG_DIR}_" == "__" ]; then
	LOG_DIR=/tmp/${USER}-${DB_EXE_BASENAME}-${PORT}/log
fi
mkdir -pv "${LOG_DIR}";
LOG_DIR=`readlink -vf "${LOG_DIR}"`

echo
echo BASE_DIR=$BASE_DIR
echo DATA_DIR=$DATA_DIR
echo LOG_DIR=$LOG_DIR
echo PORT=$PORT
if [ -n "$LD_LIBRARY_PATH" ]; then
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
fi
echo

$LAUNCH_PREFIX $DB_EXE_PATH \
 --no-defaults \
 --basedir=$BASE_DIR \
 --datadir=$DATA_DIR \
 --general-log-file=${LOG_DIR}/mysqld.log \
 --port=${PORT} \
 --pid-file=${DATA_DIR}/mysqld.pid \
 --socket=${DATA_DIR}/mysql.sock \
 --default_authentication_plugin=mysql_native_password \
 --myisam_sort_buffer_size=64M \
 --innodb_log_buffer_size=256M \
 --innodb_sort_buffer_size=1M \
 --read_buffer_size=128K \
 --read_rnd_buffer_size=256K \
 --max_allowed_packet=64M \
 --net_buffer_length=16K \
 --sort_buffer_size=1M \
 --tmp_table_size=64M \
 --max_heap_table_size=512M \
 --thread_cache_size=16 &

DB_EXE_BASENAME=`basename "$DB_EXE_PATH"`
sleep 3
ps auxwww \
	| grep -i "^USER\|$DB_EXE_BASENAME" \
	| grep -v grep \
	| grep -v launch-mysqld \
	| sed -e's/\(.*\)/\1\n/'


if [ -e "$BASE_DIR/bin/mariadb" ]; then
	CLIENT_EXE="$BASE_DIR/bin/mariadb"
elif [ -e "$BASE_DIR/bin/mysql" ]; then
	CLIENT_EXE="$BASE_DIR/bin/mariadb"
elif [ "$DB_EXE_BASENAME" == "mariadbd" ]; then
	CLIENT_EXE="maridb"
else
	CLIENT_EXE="mysql"
fi

echo "example connect string:"
echo "	$CLIENT_EXE --port=$PORT --host=127.0.0.1 --user=root@localhost"
