#!/bin/bash

IN_FILE=$1
OUT_FILE=$2

# Any block size is probably good enough;
# experimenting on my own systems has not
# shown a great difference between various
# values over 4096. Letting "dd" chose a
# value seems pretty good.
BLOCK_SIZE=$3
if [ "_${BLOCK_SIZE}_" == "__" ]; then
   BLOCK_SIZE=32768
fi;
BS=""
if [ "_${BLOCK_SIZE}_" != "_0_" ]; then
  BS="bs=${BLOCK_SIZE}"
fi;

# If the IN_FILE is a regular file, we can use the ls command
# to determine the vale; if it is a /dev/sda2 or similar,
# it might be easier just to pass it in, but this will try
# to make a good guess based on "df -B1".
SIZE=$4
if [ "_${SIZE}_" == "__" ]; then
   if [[ ${IN_FILE} == /dev/* ]]; then
       SIZE=$(df -B1 | grep ${IN_FILE} | awk '{ print $2 }')
   else
       SIZE=$(ls -l ${IN_FILE} | cut -d' ' -f5 | sed -e 's/,//g')
   fi;
fi

echo "dd ${BS} if=${IN_FILE} 2>/dev/null | pv -tpreb -s${SIZE} | dd ${BS} of=${OUT_FILE}"
dd ${BS} if=${IN_FILE} 2>/dev/null | pv -tpreb -s${SIZE} | dd ${BS} of=${OUT_FILE}
