#!/bin/bash
#
# cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1

if [ "_${VERBOSE}_" != "__" ] && [ "${VERBOSE}" -gt 0 ]; then
	set -x
fi

if [ "_$1_" == "__" ]; then
	RANDOM_STRING_LENGTH=32
else
	RANDOM_STRING_LENGTH=$1
fi

if [ "_${2,,}_" == "_base64_" ]; then
	RANDOM_STRING_CHARS="a-zA-Z0-9+/"
elif [ "_${2,,}_" == "_posix_" ]; then
	# https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282
	RANDOM_STRING_CHARS="a-zA-Z0-9\._\-"
else
	RANDOM_STRING_CHARS="a-zA-Z0-9"
fi

cat /dev/urandom \
	| tr --delete --complement "$RANDOM_STRING_CHARS" \
	| fold --width=$RANDOM_STRING_LENGTH \
	| head --lines=1
