#!/bin/bash
# https://xkcd.com/936/

if [ -z "$VERBOSE" ]; then VERBOSE=0; fi
if [ "$VERBOSE" -gt 1 ]; then set -x; fi
set -e
set -o pipefail

if [ -n "$1" ]; then
	NUM_WORDS=$(( 0 + $1 ))
else
	NUM_WORDS=4
fi

SEP=$( echo '. - _ , / + ; :' | tr ' ' '\n' | shuf | head -n 1 )
SEP_CNT=8

# SHUFFLED=$(shuf /usr/share/dict/american-english)
CANDIDATE_WORDS=$(grep -v '[^A-Za-z\-]' /usr/share/dict/american-english)
SHUFFLED=$(shuf <<< "$CANDIDATE_WORDS")
TOPX=$(head -n$NUM_WORDS <<< "$SHUFFLED")
ASONE=$(tr '\n' "$SEP" <<< "$TOPX")
DIGIT=$((RANDOM % 10))
RESULT="$ASONE$DIGIT"

# ensure at least one uppercase letter for dumb password constraints
if ! [[ "$RESULT" =~ [A-Z] ]]; then
	RESULT="$(tr '[:lower:]' '[:upper:]' <<< ${RESULT:0:1})${RESULT:1}"
fi

if [ "$VERBOSE" -gt 0 ]; then
	WORD_CNT=$(wc -l <<< "$SHUFFLED")
	COMBOS=$( bc -l <<< "( $WORD_CNT ^ $NUM_WORDS ) * $SEP_CNT * 10" )
	BITS=$( bc -l <<< "scale=1; l($COMBOS)/l(2)" )
	echo "combinations: $COMBOS (bits: $BITS, from $WORD_CNT words)"
fi

echo "$RESULT"
